automation: !include_dir_merge_list automation/
command_line: !include_dir_merge_list command_line/
template:
  - binary_sensor: !include_dir_merge_list template_binary_sensor/
  - sensor: !include_dir_merge_list template_sensor/
